import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import webpush from "web-push";

function parseEnv(text: string): Record<string, string> {
  return text
    .split("\n")
    .filter((line) => line.trim() && !line.trim().startsWith("#"))
    .reduce<Record<string, string>>((acc, line) => {
      const index = line.indexOf("=");
      if (index === -1) return acc;
      const key = line.slice(0, index).trim();
      const raw = line.slice(index + 1).trim();
      acc[key] = raw.replace(/^"/, "").replace(/"$/, "");
      return acc;
    }, {});
}

export async function ensureLocalPushConfig(envPath = path.resolve(".env.local")) {
  let original: string;
  try {
    original = await readFile(envPath, "utf8");
  } catch {
    original = "";
  }

  const parsed = parseEnv(original);

  if (
    parsed.WEB_PUSH_VAPID_SUBJECT &&
    (parsed.NEXT_PUBLIC_WEB_PUSH_VAPID_PUBLIC_KEY || parsed.WEB_PUSH_VAPID_PUBLIC_KEY) &&
    parsed.WEB_PUSH_VAPID_PRIVATE_KEY
  ) {
    return {
      wroteKeys: false,
      publicKey: parsed.NEXT_PUBLIC_WEB_PUSH_VAPID_PUBLIC_KEY ?? parsed.WEB_PUSH_VAPID_PUBLIC_KEY,
    };
  }

  const keys = webpush.generateVAPIDKeys();
  const subject = parsed.WEB_PUSH_VAPID_SUBJECT || "mailto:local-real-system-test@alwayscare.local";
  const block = [
    "",
    "# Auto-generated by real-system-validation test harness",
    `WEB_PUSH_VAPID_SUBJECT="${subject}"`,
    `NEXT_PUBLIC_WEB_PUSH_VAPID_PUBLIC_KEY="${keys.publicKey}"`,
    `WEB_PUSH_VAPID_PRIVATE_KEY="${keys.privateKey}"`,
    "",
  ].join("\n");

  await writeFile(envPath, original.trimEnd() + block);

  return {
    wroteKeys: true,
    publicKey: keys.publicKey,
  };
}
